export const KEYDATA_EN = [
  { value: "`", shiftValue: "~", class: "key key__switched", id: "Backquote" },
  { value: "1", shiftValue: "!", class: "key key__switched", id: "Digit1" },
  { value: "2", shiftValue: "@", class: "key key__switched", id: "Digit2" },
  { value: "3", shiftValue: "#", class: "key key__switched", id: "Digit3" },
  { value: "4", shiftValue: "$", class: "key key__switched", id: "Digit4" },
  { value: "5", shiftValue: "%", class: "key key__switched", id: "Digit5" },
  { value: "6", shiftValue: "^", class: "key key__switched", id: "Digit6" },
  { value: "7", shiftValue: "&", class: "key key__switched", id: "Digit7" },
  { value: "8", shiftValue: "*", class: "key key__switched", id: "Digit8" },
  { value: "9", shiftValue: "(", class: "key key__switched", id: "Digit9" },
  { value: "0", shiftValue: ")", class: "key key__switched", id: "Digit0" },
  { value: "-", shiftValue: "_", class: "key key__switched", id: "Minus" },
  { value: "=", shiftValue: "+", class: "key key__switched", id: "Equal" },
  { value: "Backspace", class: "key key__optional key_xxl", id: "Backspace" },
  {
    value: "Tab",
    shiftValue: "`",
    class: "key key__optional key_l",
    id: "Tab",
  },
  { value: "q", class: "key key__letter", id: "KeyQ" },
  { value: "w", class: "key key__letter", id: "KeyW" },
  { value: "e", class: "key key__letter", id: "KeyE" },
  { value: "r", class: "key key__letter", id: "KeyR" },
  { value: "t", class: "key key__letter", id: "KeyT" },
  { value: "y", class: "key key__letter", id: "KeyY" },
  { value: "u", class: "key key__letter", id: "KeyU" },
  { value: "i", class: "key key__letter", id: "KeyI" },
  { value: "o", class: "key key__letter", id: "KeyO" },
  { value: "p", class: "key key__letter", id: "KeyP" },
  {
    value: "[",
    shiftValue: "{",
    class: "key key__switched",
    id: "BracketLeft",
  },
  {
    value: "]",
    shiftValue: "}",
    class: "key key__switched",
    id: "BracketRight",
  },
  {
    value: `'\'`,
    shiftValue: "|",
    class: "key key__switched",
    id: "Backslash",
  },
  { value: "Del", class: "key key__optional key_l", id: "Delete" },
  { value: "CapsLock", class: "key key__optional key_xxl", id: "CapsLock" },
  { value: "a", class: "key key__letter", id: "KeyA" },
  { value: "s", class: "key key__letter", id: "KeyS" },
  { value: "d", class: "key key__letter", id: "KeyD" },
  { value: "f", class: "key key__letter", id: "KeyF" },
  { value: "g", class: "key key__letter", id: "KeyG" },
  { value: "h", class: "key key__letter", id: "KeyH" },
  { value: "j", class: "key key__letter", id: "KeyJ" },
  { value: "k", class: "key key__letter", id: "KeyK" },
  { value: "l", class: "key key__letter", id: "KeyL" },
  { value: ";", shiftValue: ":", class: "key key__switched", id: "Semicolon" },
  { value: "'", shiftValue: '"', class: "key key__switched", id: "Quote" },
  { value: "Enter", class: "key key__optional key_xl", id: "Enter" },
  {
    value: "Shift",
    class: "key key__optional shift__left key_xxl",
    id: "ShiftLeft",
  },
  { value: "z", class: "key key__letter", id: "KeyZ" },
  { value: "x", class: "key key__letter", id: "KeyX" },
  { value: "c", class: "key key__letter", id: "KeyC" },
  { value: "v", class: "key key__letter", id: "KeyV" },
  { value: "b", class: "key key__letter", id: "KeyB" },
  { value: "n", class: "key key__letter", id: "KeyN" },
  { value: "m", class: "key key__letter", id: "KeyM" },
  { value: ",", shiftValue: "<", class: "key key__switched", id: "Comma" },
  { value: ".", shiftValue: ">", class: "key key__switched", id: "Period" },
  { value: "/", shiftValue: "?", class: "key key__switched", id: "Slash" },
  { value: "&#9206;", class: "key key__arrow key__arrow_up", id: "ArrowUp" },
  {
    value: "Shift",
    class: "key key__optional shift__right key_xl",
    id: "ShiftRight",
  },
  { value: "Ctrl", class: "key key__optional ctrl__left", id: "ControlLeft" },
  { value: "Win", class: "key key__optional", id: "MetaLeft" },
  { value: "Alt", class: "key key__optional", id: "AltLeft" },
  { value: "", shiftValue: "", class: "key key__space", id: "Space" },
  { value: "Alt", class: "key key__optional", id: "AltRight" },
  {
    value: "&#9204;",
    class: "key key__arrow key__arrow_left",
    id: "ArrowLeft",
  },
  {
    value: "&#9207;",
    class: "key key__arrow key__arrow_down",
    id: "ArrowDown",
  },
  {
    value: "&#9205;",
    class: "key key__arrow key__arrow_right",
    id: "ArrowRight",
  },
  { value: "Ctrl", class: "key key__optional ctrl__right", id: "ControlRight" },
];
