export const KEYDATA_EN = [
  { value: "`", shiftValue: "~", class: "key key__switched" },
  { value: "1", shiftValue: "!", class: "key key__switched" },
  { value: "2", shiftValue: "@", class: "key key__switched" },
  { value: "3", shiftValue: "#", class: "key key__switched" },
  { value: "4", shiftValue: "$", class: "key key__switched" },
  { value: "5", shiftValue: "%", class: "key key__switched" },
  { value: "6", shiftValue: "^", class: "key key__switched" },
  { value: "7", shiftValue: "&", class: "key key__switched" },
  { value: "8", shiftValue: "*", class: "key key__switched" },
  { value: "9", shiftValue: "(", class: "key key__switched" },
  { value: "0", shiftValue: ")", class: "key key__switched" },
  { value: "-", shiftValue: "_", class: "key key__switched" },
  { value: "Backspace", class: "key key__optional" },
  { value: "Tab", shiftValue: "`", class: "key key__optional" },
  { value: "q", class: "key key__letter" },
  { value: "w", class: "key key__letter" },
  { value: "e", class: "key key__letter" },
  { value: "r", class: "key key__letter" },
  { value: "t", class: "key key__letter" },
  { value: "y", class: "key key__letter" },
  { value: "u", class: "key key__letter" },
  { value: "i", class: "key key__letter" },
  { value: "o", class: "key key__letter" },
  { value: "p", class: "key key__letter" },
  { value: "[", shiftValue: "{", class: "key key__switched" },
  { value: "]", shiftValue: "}", class: "key key__switched" },
  { value: `'\'`, shiftValue: "|", class: "key key__switched" },
  { value: "Del", class: "key key__optional" },
  { value: "CapsLock", class: "key key__optional" },
  { value: "a", class: "key key__letter" },
  { value: "s", class: "key key__letter" },
  { value: "d", class: "key key__letter" },
  { value: "f", class: "key key__letter" },
  { value: "g", class: "key key__letter" },
  { value: "h", class: "key key__letter" },
  { value: "j", class: "key key__letter" },
  { value: "k", class: "key key__letter" },
  { value: "l", class: "key key__letter" },
  { value: ";", shiftValue: "", class: "key" },
  { value: "'", shiftValue: "", class: "key" },
  { value: "Enter", class: "key key__optional" },
  { value: "Shift", class: "key key__optional" },
  { value: "z", class: "key key__letter" },
  { value: "x", class: "key key__letter" },
  { value: "c", class: "key key__letter" },
  { value: "v", class: "key key__letter" },
  { value: "b", class: "key key__letter" },
  { value: "n", class: "key key__letter" },
  { value: "m", class: "key key__letter" },
  { value: ",", shiftValue: "<", class: "key key__switched" },
  { value: ".", shiftValue: ">", class: "key key__switched" },
  { value: "/", shiftValue: "?", class: "key key__switched" },
  { value: "AU", class: "key key__arrow key__arrow_up" },
  { value: "Shift", class: "key key__optional" },
  { value: "Ctrl", class: "key key__optional" },
  { value: "Win", class: "key key__optional" },
  { value: "Alt", class: "key key__optional" },
  { value: "", shiftValue: "", class: "key key__space" },
  { value: "Alt", class: "key key__optional" },
  { value: "AL", class: "key key__arrow key__arrow_left" },
  { value: "AD", class: "key key__arrow key__arrow_down" },
  { value: "AR", class: "key key__arrow key__arrow_right" },
  { value: "Ctrl", class: "key key__optional" },
];
